build:
    image: registry.vokal.io/web
    environment:
        - REPO_OWNER=vokal
        - REPO_NAME=mannco-web
    commands:
        - npm i --silent
        # - chmod +x run-build.sh
        # - ./run-build.sh
deploy:
    script:
        image: vokal/drone-web-deployment
        commands:
            - deploy --env=prod --aws-access-key-id=$$awsAccessKey --aws-secret-access-key=$$awsSecretKey --gitver=$$COMMIT
            - notification_slack --env=dev --gitver=$$COMMIT --slacktoken=$$slackToken
