build:
    image: registry.vokal.io/web
    commands:
        - npm install
        - bower --allow-root install
        - chmod +x run-build.sh
        - ./run-build.sh
deploy:
    script:
        image: vokal/drone-web-deployment
        commands:
            - npm install
            - grunt deployprod --aws-access-key-id=$$awsAccessKey --aws-secret-access-key=$$awsSecretKey --gitver=$(git rev-parse --short HEAD)
